### ISSUE TITLE
Bug- reload and share case with overlays, pops a "not part of the case" notification while loading

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#952] opened 2017-12-10 15:14 UTC
**Current behavior** 
Reload and share case with overlays, pops a "not part of the case" notification while loading. after the overlay is loaded the notification disappears. 

**Expected behavior** 
No notification at all, unless needed. 

**Minimal reproduction of the problem with instructions** 
Try to share and reload exciting case with overlays.

**Comment by asafMasa** [comment] 2017-12-24 08:49
@carmelorr @idanbarak it is by design, recommend to close it

**Comment by idanbarak** [comment] 2017-12-25 09:54
OK

**Closed** 2018-01-07 14:28 UTC
Labels: Bug, Severity: Low
