### ISSUE TITLE
authentication problem notification

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1227] opened 2018-02-20 15:47 UTC
@asafMasa can you please see if you get 402/401 error?
if so, please add the notification

**Comment by carmelorr** [comment] 2018-02-21 12:29
![10 8 5](https://user-images.githubusercontent.com/26301386/36480053-9261be5c-1713-11e8-959f-eeaccb52530c.png)

**Comment by asafMasa** [comment] 2018-03-29 13:13
@carmelorr @idanbarak What if 1 provider returned 401 and the other returned valid overlays?

**Comment by idanbarak** [comment] 2018-04-01 05:39
@asafMasa 
Shoe notification regarding failed provider and show overlays on timeline..
that is one of the reasons we have enabled the notification and overlays to be displayed simultaneously

**Comment by carmelorr** [comment] 2018-07-03 05:37
@asafMasa please see issue #1430 for current design

**Comment by asafMasa** [comment] 2018-08-23 14:04
@carmelorr @idanbarak By design no error is returned, only empty collection.
i think we should close this issue

**Comment by carmelorr** [comment] 2018-08-26 06:32
@asafMasa this is related to https://github.com/AnSyn/ansyn/issues/1430

**Closed** 2019-04-17 07:24 UTC
Labels: Blocked, Ready for UI Design Review, Ready for: Design, Severity: High
